- id: clean_bathroom
  alias: "Прибрати ванну"
  trigger:
    - platform: state
      entity_id: sensor.kid_bathroom_button_action
      to: single
      variables:
        bathroom_id: child_bathroom
    - platform: state
      entity_id: sensor.master_bathroom_button_action
      to: single
      variables:
        bathroom_id: master_bathroom
  action:
    - service: script.vacuum_clean
      data:
        rooms: 
          - "{{ bathroom_id }}"
  mode: queued

- id: clean_zone
  alias: "Прибрати зону"
  trigger:
    - platform: state
      entity_id: sensor.fireplace_button_action
      to: single
      variables:
        zone_name: fireplace
  action:
    - service: script.vacuum_clean_zone
      data:
        zones:
          - "{{ zone_name }}"
  mode: queued

- id: clean_house
  alias: Прибирання будинку
  trigger:
    - platform: time
      at:
        - "09:00:00"
        - "17:00:00"
    - platform: state
      entity_id:
        - group.residents
      to: not_home
    - platform: event
      event_type: telegram_command
      event_data:
        command: /clean_house
      variables:
        force_clean: true
  condition:
    - alias: Форсоване прибирання або сьогодні не неділя і ще не прибиралось
      condition: template
      value_template: |
        {{ 
          force_clean is defined and force_clean or
          as_datetime(states('input_datetime.last_cleaned_at')).strftime('%Y-%m-%d') != utcnow().strftime("%Y-%m-%d")
          and now().strftime('%a') != 'Sun'
        }}
  action:
    - if:
        - condition: or
          conditions:
            - condition: state
              entity_id: group.residents
              state: not_home
            - condition: template
              value_template: "{{ force_clean is defined and force_clean }}"
              alias: Force clean
          alias: Нас нема вдома або підтверджене прибирання
      then:
        - service: script.vacuum_clean
          alias: Почати прибирання
          data:
            rooms: "{{ states('sensor.rooms_to_clean_today') | from_json }}"
        - service: input_datetime.set_datetime
          data:
            date: "{{ now().strftime('%Y-%m-%d') }}"
          target:
            entity_id: input_datetime.last_cleaned_at
      else:
        - service: notify.telegram_serhii
          data:
            message: |
              Час поприбирати зміщено на коли Ви покинете будинок. Буде прибрано:
              - {{ states('sensor.rooms_to_clean_today') | from_json | join('\n -') }}
              Щоб прибрати зараз тисни /clean\_house
          alias: Сповіщення про прибирання
  mode: single
