input_boolean:
  skip_child_zone: 
    name: Не прибирати дитячу зону у вітальні

input_datetime:
  last_cleaned_at:
    name: Дата останнього прибрання
    has_date: true
    has_time: false

template: 
  - sensor:
    - name: rooms_to_clean_today
      state: >-
        {% set rooms_to_clean = [
          "hall",
          "coming_room",
          "living_room_table",
          "kitchen"
        ] %} 
        {% set week_day = now().isoweekday() %}
        
        {% if week_day % 2 == 0 or week_day == 6 %} 
          {% set rooms_to_clean = rooms_to_clean + [
            "bedroom_kid_small",
            "bedroom_kid_big",
            "child_bathroom"
          ]%}

          {% if states('input_boolean.skip_child_zone') == 'off' %}
            {% set rooms_to_clean = rooms_to_clean + ["living_room_entertainment"] %}
          {% endif %}
        {% endif %}

        {% if week_day % 2 != 0 or week_day == 6 %}
          {% set rooms_to_clean = rooms_to_clean + [
            "master_bathroom",
            "master_bedroom",
            "wardrobe",
            "cabinet"
          ]%}
        {% endif %}

        {{ rooms_to_clean | to_json }}

script:
  vacuum_clean:
    alias: Vacuum clean rooms
    mode: restart
    icon: mdi:robot-vacuum
    description: |
      Cleans specified rooms by their names
    fields:
      rooms:
        name: Rooms to clean
        required: true
        selector:
          select:
            multiple: true
            options:
            - ALL
            - bedroom_kid_small
            - bedroom_kid_big
            - cabinet
            - kitchen
            - coming_room
            - living_room_table
            - child_bathroom
            - master_bedroom
            - wardrobe
            - living_room_entertainment
            - master_bathroom
            - hall
    variables:
      roomsIds: |
        {% 
          set all_rooms = [
            { "label": "bedroom_kid_small", "id": 16 },
            { "label": "bedroom_kid_big", "id": 17 },
            { "label": "cabinet", "id": 18 },
            { "label": "kitchen", "id": 19 },
            { "label": "coming_room", "id": 20 },
            { "label": "living_room_table", "id": 21 },
            { "label": "child_bathroom", "id": 27 },
            { "label": "master_bedroom", "id": 23 },
            { "label": "wardrobe", "id": 24 },
            { "label": "living_room_entertainment", "id": 25 },
            { "label": "master_bathroom", "id": 26 },
            { "label": "hall", "id": 22 }
          ]
        %} 
        {% if 'ALL' in rooms %}
          {{ all_rooms | map(attribute="id") | list }}
        {% else %}
          {{ all_rooms 
            | selectattr('label', 'in', rooms)
            | map(attribute="id")
            | list 
          }}
        {% endif %}
    sequence:
    - service: notify.telegram_serhii
      data:
        message: |
          Брюс почав прибирання:
          {{ rooms | join("\n") }}
    - service: vacuum.send_command
      data:
        command: app_segment_clean
        params: "{{ roomsIds }}"
      target:
        entity_id: vacuum.bruce

  vacuum_clean_zone:
    alias: Vacuum clean zones
    icon: mdi:robot-vacuum
    mode: single
    fields:
      zones:
        name: Zone names to clean
        required: true
        selector:
          select:
            multiple: true
            options:
              - terrace_exit
              - fireplace
              - livingroom_entertainment
    variables:  
      zones_coords: |
        {% 
          set coords = [
            { "label": "livingroom_entertainment", "value": [24100,25160,27340,28220] },
            { "label": "terrace_exit", "value": [26033,25167,27317,27283] },
            { "label": "fireplace", "value": [21825,25800,24350,27350] }
          ]
        %}
        {{ coords 
          | selectattr('label', 'in', zones)
          | map(attribute="value")
          | list  
        }}
    sequence: 
      - condition: state
        entity_id: vacuum.bruce
        state: docked
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          repeats: 2
          zone: "{{ zones_coords }}"
        target:
          entity_id: vacuum.bruce
      
automation: !include ./automations.yml