- id: notify_about_garage_gates_state
  alias: "Гараж: Повідомлення про стан гаражних воріт"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_gates_left_open_contact
    - platform: state
      entity_id: binary_sensor.garage_gates_right_open_contact
  action:
    - event: important_home_event
      event_data:
        message: >-
          {{ "Ліві" if "_left_" in trigger.entity_id else "Праві" }} ворота 
          {{ "відкрито" if trigger.to_state.state == "on" else "закрито" }}
          ({{ trigger.to_state.state }})
  mode: parallel

- id: ensure_gates_are_closed
  alias: "Гараж: Закрити ворота"
  trigger:
    - platform: state
      entity_id: group.residents
      to: not_home
    - platform: event
      event_type: external_command
      event_data:
        command: /close_garage_gates
    - platform: state
      entity_id: binary_sensor.is_main_door_unlocked
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.is_terace_door_unlocked
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.garage_gates_left_open
        - switch.garage_gates_right_open
  mode: single

- id: power_off_garage_gates_when_closed
  alias: "Гараж: Вимкнути живлення на ворота, коли закрились"
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.garage_gates_left_open_contact
        - binary_sensor.garage_gates_right_open_contact
      to: 'off'
      variables:
        power_off_at: "{{ now() + timedelta(seconds=10) }}"
    - platform: state
      entity_id: 
        - binary_sensor.garage_gates_left_open_contact
        - binary_sensor.garage_gates_right_open_contact
      to: "on"
      variables:
        force_power_off: true
        power_off_at: "{{ now() + timedelta(minutes=15) }}"
  condition:
    - condition: template
      value_template: | 
        {{ 
          is_state('binary_sensor.garage_gates_left_open_contact', 'off') and
          is_state('binary_sensor.garage_gates_right_open_contact', "off") or 
          force_power_off is defined and force_power_off
        }}
  action:
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.power_off_garage_gates_at
      data:
        datetime: "{{ power_off_at }}"
  mode: single

- id: power_on_garage_gates_when_exit_house
  mode: single
  alias: "Ввімкнути живлення на ворота, коли виходжу з будинку"
  trigger:
    - platform: event
      event_type: yard_crossed_line
      event_data:
        name: house_near_stairs
        direction: LeftToRight
      variables:
        is_human: |
          {{ is_state('binary_sensor.camera_house_entrance_smart_motion_human', 'on') }}
    - platform: event
      event_type: yard_crossed_line
      event_data:
        name: house_garage_gates_direction
        direction: LeftToRight
      variables:
        is_human: | 
          {{ is_state('binary_sensor.camera_between_house_and_garage_smart_motion_human', 'on') }}
    - platform: event
      event_type: yard_crossed_line
      event_data:
        name: garage_home_direction
        object_type: Human
        direction: LeftToRight
      variables:
        is_human: true
    - platform: event
      event_type: yard_crossed_line
      event_data:
        name: yard_gates
        object_type: Human
        direction: LeftToRight
      variables:
        is_human: true
  condition:
    - condition: template
      alias: Gates are closed and powered off
      value_template: |
        {{ 
          is_state('binary_sensor.garage_gates_left_open_contact', 'off') and
          is_state('binary_sensor.garage_gates_right_open_contact', 'off') and
          is_state('switch.garage_gates_power', 'off') and is_human
        }}
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.garage_gates_power
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.power_off_garage_gates_at
      data:
        datetime: "{{ now() + timedelta(minutes=5) }}"

- id: power_off_gates_at_specified_time
  mode: single
  trigger:
    platform: time
    at: input_datetime.power_off_garage_gates_at
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.garage_gates_power
    - if:
        - condition: template
          value_template: |
            {{ 
              is_state('binary_sensor.garage_gates_left_open_contact', 'on') or
              is_state('binary_sensor.garage_gates_right_open_contact', 'on')
            }}
      then:
        - event: important_home_event
          event_data:
            message: >-
              Вимикаю живлення на воротах. 
              Тисни /close_garage_gates, щоб закрити їх

# - id: open_garage_gate_when_going_out
#   mode: single
#   trigger:
#     platform: state
#     entity_id: binary_sensor.is_main_door_unlocked
#     from: 'on'
#     to: 'off'
#   condition:
#     - condition: template
#       value_template: "{{ is_state('group.residents', 'home') }}"
#   action:
#     - wait_for_trigger:
#         platform: event
#         event_type: yard_crossed_line
#         event_data: 
#           name: house_near_stairs
#           direction: LeftToRight
#       timeout: "00:05"
#       continue_on_timeout: false
#     - wait_template: "{{ is_state('binary_sensor.camera_house_entrance_smart_motion_human', 'on') }}"
#       timeout: "00:00:30"
#       continue_on_timeout: false
#     - wait_for_trigger:
#         platform: event
#         event_type: yard_crossed_line
#         event_data:
#           name: garage_home_direction
#           direction: LeftToRight
#           object_type: Human
#       timeout: "00:05:00"
#       continue_on_timeout: false
#     - wait_for_trigger:
#         platform: event
#         event_type: yard_crossed_line
#         event_data:
#           name: yard_gates
#           direction: LeftToRight
#           object_type: Human
#       timeout: "00:05:00"
#       continue_on_timeout: false
#     - condition: template
#       value_template: "{{ is_state('group.residents', 'home') }}"
#     - service: switch.turn_on
#       target:
#         entity_id: switch.garage_gates_left_open