input_datetime:
  power_off_garage_gates_at:
    name: Дата вимкнення воріт гаража
    has_date: true
    has_time: true

switch:
  - platform: template
    switches:
      garage_gates_left_open:
        friendly_name: Ліві гаражні ворота
        value_template: "{{ is_state('binary_sensor.garage_gates_left_open_contact', 'on') }}"
        availability_template: "{{ has_value('switch.garage_gates_left_trigger') }}"
        turn_on:
          - if:
            - condition: template
              value_template: "{{ is_state('switch.garage_gates_power', 'off') }}"
            then:
            - service: switch.turn_on
              entity_id: switch.garage_gates_power
            - wait_template: "{{ float(states('sensor.garage_gates_power_current'), 0) >= 0.1 }}"
              timeout: "00:00:05"
          - service: switch.toggle
            target:
              entity_id: switch.garage_gates_left_trigger
        turn_off:
          - service: switch.toggle
            target:
              entity_id: switch.garage_gates_left_trigger
        icon_template: >-
          {% if is_state('binary_sensor.garage_gates_left_open_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
      garage_gates_right_open:
        friendly_name: Праві гаражні ворота
        value_template: "{{ is_state('binary_sensor.garage_gates_right_open_contact', 'on') }}"
        availability_template: |
          {{ 
            has_value('binary_sensor.garage_gates_right_open_contact') and
            has_value('switch.garage_gates_bot_right')
          }}
        turn_on:
          service: script.toggle_garage_gate
          data:
            gate: right
            state: true
        turn_off:
          service: script.toggle_garage_gate
          data:
            gate: right
            state: false
        icon_template: >-
          {% if is_state('binary_sensor.garage_gates_right_open_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

script: !include ./scripts.yml
automation: !include ./automations.yml