input_datetime:
  power_off_garage_gates_at:
    name: Дата вимкнення воріт гаража
    has_date: true
    has_time: true

template:
  - binary_sensor:
    - name: garage_gates_right_open_contact
      state: "{{ is_state('switch.garage_gates_right_open_contact', 'on') }}"

switch:
  - platform: template
    switches:
      garage_gates_left_open:
        friendly_name: Ліві гаражні ворота
        value_template: "{{ is_state('binary_sensor.garage_gates_left_open_contact', 'on') }}"
        availability_template: "{{ has_value('switch.garage_gates_left_trigger') }}"
        turn_on:
          service: script.toggle_garage_gate
          data:
            gate: left
            state: true
        turn_off:
          service: script.toggle_garage_gate
          data:
            gate: left
            state: false
        icon_template: >-
          {% if is_state('binary_sensor.garage_gates_left_open_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
      garage_gates_right_open:
        friendly_name: Праві гаражні ворота
        value_template: "{{ is_state('binary_sensor.garage_gates_right_open_contact', 'on') }}"
        availability_template: |
          {{ has_value('switch.garage_gates_right_trigger') }}
        turn_on:
          service: script.toggle_garage_gate
          data:
            gate: right
            state: true
        turn_off:
          service: script.toggle_garage_gate
          data:
            gate: right
            state: false
        icon_template: >-
          {% if is_state('binary_sensor.garage_gates_right_open_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

script: !include ./scripts.yml
automation: !include ./automations.yml