automation:
  - id: set_brightness_level
    alias: Set brightness level
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: sleeping_time_start
      - platform: event
        event_type: sleeping_time_end
    variables:
      brightness: |
        {% set is_night = 21 < now().hour or now().hour < 7 %}

        {{{
          'kid_bathroom': 58 if is_night else 255
        }}}
    action:
      - service: light.turn_on
        data:
          brightness: "{{ brightness.kid_bathroom }}"
        target:
          entity_id: light.kid_bathroom
      - service: light.turn_off
        target:
          entity_id: light.kid_bathroom