input_boolean:
  skip_irrigation_today:
    name: Не поливати сьогодні

automation:
  - id: toggle_irrigation_on_condition
    alias: Disable irrigation on condition
    trigger:
      - platform: state
        entity_id: input_boolean.skip_irrigation_today
        to: ['on', 'off']
      # TODO: add condition to delay irrigation if battery is low
    variables:
      irrigation_enabled: "{{ is_state('input_boolean.skip_irrigation_today', 'off') }}"
    action:
      - service: irrigation_unlimited.adjust_time
        data:
          entity_id: binary_sensor.irrigation_unlimited_c1_m
          percentage: >
            {% if irrigation_enabled %}
              {% set multiplier = 1.0 %}
            {% else %}
              {% set multiplier = 0.0 %}
            {% endif %}

            {{ (multiplier * 100) | round(0) }}

  - id: disable_skip_irrigation
    alias: Disable skip irrigation
    trigger:
      - platform: time
        at: "23:59:59"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.skip_irrigation_today

irrigation_unlimited:
  controllers:
    check_back:
      delay: 3
      retries: 100
    all_zones_config:
      show:
        timeline: true
    zones:
      - name: "Near garage"
        zone_id: near_garage
        entity_id: "switch.watering_near_garage"
      - name: "Trees"
        zone_id: trees
        entity_id: "switch.watering_bed2"
      - name: "Beds toilet"
        zone_id: beds_toilet
        entity_id: "switch.watering_bed"
      - name: "Back yard"
        zone_id: back_yard
        entity_id: "switch.watering_back_yard"
    sequences:
      - name: "Sunrise"
        schedules:
        - name: "Sunrise"
          time:
            sun: "sunrise"
            after: "00:30:00"
        zones:
        - zone_id: near_garage
          duration: "00:15:00"
        - zone_id: back_yard
          duration: "00:15:00"
      - name: "Sunset"
        schedules:
        - name: "Sunset"
          day: "odd"
          time:
            sun: "sunset"
            before: "02:00:00"
        zones:
        - zone_id: trees
          duration: "00:15:00"
        - zone_id: beds_toilet
          duration: "00:20:00"
