automation:
  - id: toggle_kitchen_light
    alias: Kitchen light control
    mode: restart
    trigger:  
      # - platform: mqtt
      #   topic: zb2mqtt/kitchen_main_light_toggler
      #   variables: 
      #     process_trigger: "{{ trigger.payload_json['vibration'] == true and is_state('group.residents', 'home') }}"
      #     new_state: "on"
      - platform: state
        # entity_id: binary_sensor.kitchen_motion
        entity_id: binary_sensor.kitchen_presence
        to: 'on'
        variables:
          process_trigger: "{{ is_state('binary_sensor.is_dark', 'on') }}"
          new_state: 'on'
      - platform: state
        entity_id: binary_sensor.kitchen_presence
        to: 'off'
        for: "00:03:00"
        variables:
          process_trigger: true
          new_state: "off"
    condition:
      - condition: template
        value_template: "{{ process_trigger }}"
    action:
      - service_template: "light.turn_{{ new_state }}"
        target:
          entity_id: light.kitchen_light

  - id: toggle_kitchen_bar_light
    alias: Kitchen bar light control
    mode: restart
    trigger:  
      - platform: state
        entity_id: binary_sensor.kitchen_bar_presence
        to: 'on'
        for: '00:00:03'
        variables: 
          process_trigger: "{{ is_state('binary_sensor.is_dark', 'on') }}"
          new_state: "on"
      - platform: state
        entity_id: binary_sensor.kitchen_bar_presence
        to: 'off'
        for: '00:00:30'
        variables: 
          new_state: "off"
          process_trigger: true
      # - platform: mqtt
      #   topic: zb2mqtt/kitchen_bar_light_toggler
      #   variables: 
      #     process_trigger: "{{ trigger.payload_json['vibration'] == true and is_state('group.residents', 'home') }}"
      #     new_state: "on"
    condition:
      - condition: template
        value_template: "{{ process_trigger }}"
    action:
      - service_template: "light.turn_{{ new_state }}"
        target:
          entity_id: light.kitchen_bar