- id: '1685193984125'
  alias: Leave home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.residents
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: e4edd8a8e5c41dfcd5e5fb995faae3ef
    entity_id: switch.hot_water_pump
    domain: switch
  - type: turn_off
    device_id: 39eeedbff766a6e6a7a5f477323810d5
    entity_id: light.kid_bathroom
    domain: light
  - type: turn_off
    device_id: 7963b61108aaeabc04743970d4f37081
    entity_id: light.master_bathroom
    domain: light
  mode: single
- id: '1686056821'
  alias: Керування насосу ГВП
  trigger:
  - entity_id: light.kid_bathroom
    platform: state
  - entity_id: light.master_bathroom
    platform: state
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.kitchen_motion
    platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: time
    at: 05:49:00
    variables:
      force_state: 'on'
  - platform: time
    at: 05:59:00
  - platform: state
    entity_id:
    - group.residents
    to: home
    variables:
      force_state: 'on'
  action:
  - service_template: "{% if states('binary_sensor.needs_hot_water_pump') == \"on\"
      or force_state == \"on\" %}\n  switch.turn_on\n{% else %}\n  switch.turn_off\n{%
      endif %}\n"
    entity_id:
    - switch.hot_water_pump
    alias: Ввікнути/Вимкнути насос ГВП
- id: '1686369648689'
  alias: Керування освітлення гаража
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
    variables:
      light_state: 'on'
  - platform: sun
    event: sunset
    offset: 01:00:00
    variables:
      light_state: 'off'
  - platform: time
    at: 01:00:00
    variables:
      light_state: 'off'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.residents
      state: home
    - condition: template
      value_template: '{{ light_state == "off" }}'
  action:
  - entity_id: switch.garage_light_outside
    service_template: switch.turn_{{ light_state }}
    alias: Toggle light
  mode: single
- id: '1686459780356'
  alias: Повідомлення про розряджені девайси
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.has_devices_with_low_battery
    to: 'on'
  condition: []
  action:
  - service: notify.telegram_serhii
    data:
      message: Є девайси що розрядились нижче 15%
      title: Розряджені девайси!
  mode: single
- id: '1687463732202'
  alias: 'Serhii: telegram bot based home presence'
  description: ''
  trigger:
  - platform: event
    event_type: telegram_command
    context: {}
    event_data:
      command: /back_home
    variables:
      device_tracker_state: home
  - platform: event
    event_type: telegram_command
    context: {}
    event_data:
      command: /leave_home
    variables:
      device_tracker_state: not_home
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: serhii_phone_shortcut
      location_name: '{{ device_tracker_state }}'
  mode: single
- id: '1688027239221'
  alias: Хтось в будинку коли мене нема
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: bd5da9a66aed1fda461a02ace69dc036
    entity_id: binary_sensor.kitchen_motion
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: group.residents
    state: not_home
  action:
  - service: notify.telegram_serhii
    data:
      message: Якийсь рух в будинку!!!
  mode: single
