- id: '1686056821'
  alias: Керування насосу ГВП
  trigger:
  - entity_id: light.kid_bathroom
    platform: state
  - entity_id: light.master_bathroom
    platform: state
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  - entity_id:
    - binary_sensor.kitchen_motion
    platform: state
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: time
    at: 05:49:00
    variables:
      force_state: 'on'
  - platform: time
    at: 05:59:00
  - platform: state
    entity_id:
    - group.residents
    to: home
    variables:
      force_state: 'on'
  action:
  - service_template: "{% if states('binary_sensor.needs_hot_water_pump') == \"on\"
      or force_state == \"on\" %}\n  switch.turn_on\n{% else %}\n  switch.turn_off\n{%
      endif %}\n"
    entity_id:
    - switch.hot_water_pump
    alias: Ввікнути/Вимкнути насос ГВП
- id: '1686369648689'
  alias: Керування освітлення гаража
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
    variables:
      light_state: 'on'
  - platform: sun
    event: sunset
    offset: 01:00:00
    variables:
      light_state: 'off'
  - platform: time
    at: 01:00:00
    variables:
      light_state: 'off'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.residents
      state: home
    - condition: template
      value_template: '{{ light_state == "off" }}'
  action:
  - entity_id: switch.garage_light_outside
    service_template: switch.turn_{{ light_state }}
    alias: Toggle light
  mode: single
- id: '1686459780356'
  alias: Повідомлення про розряджені девайси
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.has_devices_with_low_battery
    to: 'on'
  condition: []
  action:
  - service: notify.telegram_serhii
    data:
      message: Є девайси що розрядились нижче 15%
      title: Розряджені девайси!
  mode: single
