
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml

script: !include scripts.yaml
scene: !include scenes.yaml

template: !include template.yml

telegram_bot: 
  platform: polling
  api_key: !secret telegram_bot_key
  allowed_chat_ids: 
    - !secret telegram_bot_serhii_chat

notify:
  - platform: telegram
    name: telegram_serhii
    chat_id: !secret telegram_bot_serhii_chat

device_tracker: 

panel_iframe:
  zbhouse:
    title: House ZB
    url: http://192.168.32.10:9123/
    icon: mdi:home-automation
    require_admin: true

  zbgarage:
    title: Garage ZB
    url: http://192.168.32.10:9124/
    icon: mdi:home-automation
    require_admin: true

ebusd:
  host: '192.168.32.10'
  circuit: bai
  name: Main heater


homeassistant:
  allowlist_external_dirs:
    - "/tmp"

  packages:
    core: !include _config/core/main.yml
    heating: !include _config/heating/main.yml
    garage_gates: !include _config/garage_gates/main.yml
    electricity: !include _config/electricity/main.yml
    cleaning: !include _config/cleaning/main.yml
    ventilation: !include _config/ventilation/main.yml
    ventillation_kitchen_stove: !include _config/ventillation_kitchen_stove/main.yml
    watchtv: !include _config/watchtv/main.yml
    kitchen_light_control: !include _config/kitchen_light/main.yml
    security: !include _config/security/main.yml
    doghouse: !include _config/doghouse/main.yml
    camera: !include _config/camera/main.yml
    outside_light: !include _config/outside_light/main.yml

python_script:
ffmpeg:

logger:
  default: warning
  logs:
    homeassistant.components.python_script.heating_ebus_sync.py: info
    # custom_components.dahua: debug


lovelace:
  resources:
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module

recorder:
  auto_purge: false
  auto_repack: false
  db_url: !secret recorder_db_url
  # include:
  #   entities:

custom_jinja2_filters: