homeassistant: true
permit_join: false
frontend: true
mqtt:
  base_topic: zbgarage
advanced:
  pan_id: 6650
  log_level: warn
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
devices:
  '0xdc8e95fffe11b7d6':
    friendly_name: garage_light_outside
  '0x187a3efffe006b28':
    friendly_name: power_consumption
  '0xdc8e95fffe19a5e2':
    friendly_name: basement_light
  '0xe0798dfffecc8ab2':
    friendly_name: basement_climate
  '0xa4c138fd78701cba':
    friendly_name: water_pump
  '0x842712fffe513420':
    friendly_name: garage_yard_light
  '0xa4c138e02b828b6b':
    friendly_name: garage_gates_left_power
  '0xa4c138a744aed5f3':
    friendly_name: garage_gates_left
  '0xa4c138af0ff1fd8a':
    friendly_name: garage_gates_right_power
  '0xdc8e95fffe1e2e26':
    friendly_name: watering_bed
  '0x385b44fffe1438a1':
    friendly_name: watering_near_garage
  '0xdc8e95fffe19a5eb':
    friendly_name: watering_bed2
  '0x385b44fffe1b2520':
    friendly_name: watering_back_yard
  '0xa4c138d8fe2c2eb5':
    friendly_name: garage_front_center
  '0xa4c138c6c148a424':
    friendly_name: garage_light_inside
  '0x54ef441000d2844e':
    friendly_name: garage_light_sensor
  '0xa4c138e6e170a28a':
    friendly_name: basement_fan
  '0xa4c138e381bfdac1':
    friendly_name: garage_gates_right
device_options:
  legacy: false