- id: set_back_home_date
  alias: "Встановити час повернення додому"
  trigger:
    - platform: state
      entity_id: group.residents
      from: not_home
      to: home
  action:
    - service: input_datetime.set_datetime
      data:   
        timestamp: "{{ now().timestamp() }}"
      target:
        entity_id: input_datetime.back_home_at
  mode: single

- id: sync_device_state_with_input
  alias: Збереження трекінгу девайса
  trigger:
    - platform: state
      entity_id: person.serhii
  action:
    - service: input_text.set_value
      data: 
        value: "{{ trigger.to_state.state }}"
      target: 
        entity_id: input_text.serhii_phone_shortcut

- id: restore_device_state_on_restart
  alias: Відновити стан девайсу на перезавантаження HASS
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: device_tracker.see
      data:
        dev_id: serhii_phone_shortcut
        location_name: "{{ states('input_text.serhii_phone_shortcut') }}"

- id: sync_terace_door_open
  trigger:
    - platform: state
      entity_id: sensor.terrace_door_sensor
  action:
    - service_template: "input_boolean.turn_{{ 'off' if trigger.to_state.state == 'False' else 'on' }}"
      target:
        entity_id: input_boolean.terace_door_open

- id: disable_light_on_leave
  trigger:
    - platform: state
      entity_id: group.residents
      from: home
      to: not_home
      for: 00:05:00
  action:
    - service: switch.turn_off
      entity_id:
        - switch.garage_light_outside_2
        - switch.kid_bathroom
        - switch.master_bathroom
        - switch.kitchen_light_main
        - switch.kitchen_bar

- id: duplicate_persistent_notification_to_telegram
  trigger:
    - platform: persistent_notification
      update_type:
        - added
  action:
    - service: notify.telegram_serhii
      data:
        title: "{{ trigger.notification.title }}"
        message: "{{ trigger.notification.message }}"
