group:
  residents:
    name: Residents
    entities:
      - person.serhii

input_datetime: 
  back_home_at:
    name: Час повернення додому
    icon: mdi:home-clock
    has_date: true
    has_time: true

input_text:
  serhii_phone_shortcut:
    name: Сергій вдома?

input_boolean:
  terace_door_open:
    name: Двері на терасі

input_select:
  curtain_outside_mode:
    name: Режим ролет
    options:
      - tv_watching_light_mode
      - tv_watching_mode
      - close_panoramic
      - close_everything
      - open

counter:
  kid_bathroom_switch:
    name: К-сть перемикань світла в дитячій ванній
    step: 1
  master_bathroom_switch:
    name: К-сть перемикань світла в дорослій ванній
    step: 1

sensor:
  - platform: template
    sensors:
      some_time_at_home_passed:
        device_class: timestamp
        value_template: "{{ (states('input_datetime.back_home_at') | as_datetime | as_local) + timedelta(minutes=10) }}"
  - platform: mqtt_room
    device_id: "sd:0xfd44"
    name: Car
    state_topic: 'espresense/devices/sd:0xfd44'
    timeout: 10
    away_timeout: 10
  - platform: mqtt_room
    device_id: "iphone_serhii"
    name: serhii_iphone_room
    state_topic: 'espresense/devices/iphone_serhii'
    timeout: 10
    away_timeout: 10

template:
  - binary_sensor:  
    - name: is_dark
      state: |
        {{ 
          is_state('sun.sun', 'below_horizon') or
          now().timestamp() + 1.5 * 60 * 60 >= as_datetime(states('sensor.sun_next_setting')).timestamp() or
          now().hour >= 22 or now().hour < 1
        }}

command_line:
  - switch:
      name: water_heater_2k
      icon: mdi:water-boiler
      command_on: !secret water_heater_command_on
      command_off: !secret water_heater_command_off
      command_state: !secret water_heater_command_state
      value_template: >-
        {{ value == '"on"' }}
      # availability: "{{ value_json.error == 0 }}"

# switch:
#   - platform: command_line
#     resource: !secret water_heater_resource_url
#     # method: POST
#     body_on: !secret water_heater_body_on
#     body_off: !secret water_heater_body_off
#     value_template: "{{ value_json.error == 0 and value_json.data.switches[0].switch == 'on' }}"
#     availability: "{{ value_json.error == 0 }}"
#     scan_interval: 60
#     timeout: 100
#     headers:
#       Content-Type: application/json
#     device_class: switch
    # name: water_heater_2k
        
automation: !include ./automations.yml
script: !include ./script.yml