automation:
  - id: notify_about_moves_when_nobody_at_home
    alias: Нотифікація про рух в будинку коли нема нікого вдома
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.kitchen_motion
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ states('group.residents') == 'not_home' }}"
    action:
      - event: important_home_event
        event_data:
          message: Рух в будинку, коли нікого нема !!!