homeassistant: true
permit_join: false
frontend: true
mqtt:
  base_topic: zb2mqtt
devices:
  '0xdc8e95fffe15d3e7':
    friendly_name: master_bathroom
  '0xdc8e95fffe19bbe0':
    friendly_name: master_bathroom_towel_dryer
  '0x30fb10fffe76ff44':
    friendly_name: master_bedroom_climate
  '0xdc8e95fffe19bdaf':
    friendly_name: house_outside
  '0xa4c138757bd27eb8':
    friendly_name: kitchen_light
  '0x60b647fffe5335e2':
    friendly_name: bathroom_fan
  '0xe0798dfffecc938a':
    friendly_name: kid_bathroom_climate
  '0xe0798dfffecc830e':
    friendly_name: master_bathroom_climate
  '0xa4c13880651dc2f9':
    friendly_name: fridge
  '0xf4b3b1fffe94fdda':
    friendly_name: master_wardrobe_climate
    homeassistant: {}
    optimistic: true
    retain: true
  '0x3410f4fffec40a92':
    friendly_name: cabinet_zigbee_repeater
  '0xa4c138ac2e0ed3ed':
    friendly_name: dishwasher
  '0xa4c138aa7b9ce7bf':
    friendly_name: livingroom_tracking_light_13
  '0xa4c138d695d32ff4':
    friendly_name: livingroom_tracking_light_11
  '0xa4c13824ecc4ed30':
    friendly_name: livingroom_tracking_light_14
  '0xa4c1381acb247964':
    friendly_name: livingroom_tracking_light_12
  '0xa4c138285b382c11':
    friendly_name: livingroom_tracking_light_24
  '0xa4c138ef40675ea6':
    friendly_name: livingroom_tracking_light_22
  '0xa4c138b9501adc7a':
    friendly_name: livingroom_tracking_light_21
  '0xa4c13867e6ec9234':
    friendly_name: heater_valves
    invert_switch: false
  '0xa4c138ce682ec97e':
    friendly_name: hot_floor_pump
  '0xa4c13802a9df891a':
    friendly_name: fireplace_fan
  '0xa4c138f5d530afd4':
    friendly_name: doghouse_climate
  '0xa4c1389dd3983dd2':
    friendly_name: livingroom_outside_curtain_1
    invert_cover: false
  '0xa4c13894f4dbe43b':
    friendly_name: livingroom_outside_curtain_2
  '0xa4c1387abb3d7da0':
    friendly_name: kitchen_outside_curtain
  '0xf4b3b1fffe9922f8':
    friendly_name: living_room_climate
  '0xa4c138e918dcb971':
    friendly_name: tv_button
  '0xa4c1388c226303c4':
    friendly_name: master_bathroom_button
  '0xa4c138700aa8a343':
    friendly_name: cameras_outside_power
  '0xa4c1387555bb5cde':
    friendly_name: terrace_outside_curtain
  '0xa4c1386338cbc1c5':
    friendly_name: kid_small_outside_curtain
  '0xa4c13895caeacd23':
    friendly_name: kid_big_outside_curtain
  '0xa4c1386f295ba842':
    friendly_name: cabinet_outside_curtain
  '0xa4c1389e40e945ff':
    friendly_name: master_bedroom_outside_curtain
  '0xa4c138fa677c9617':
    friendly_name: fireplace_button
  '0xa4c13824d6b2e4b3':
    friendly_name: washing_machine
  '0xa4c13845a6713fc4':
    friendly_name: dryer
  '0x94deb8fffec54871':
    friendly_name: master_remote_control
  '0xe0798dfffecc7471':
    friendly_name: kid_big_climate
  '0xe0798dfffecc85aa':
    friendly_name: cabinet_climate
  '0xa4c13874ed7dc3c1':
    friendly_name: kitchen_socket_left1
  '0xa4c1389fc38ce599':
    friendly_name: livingroom_tv_light
    transition: 1
  '0xa4c1385c65126c30':
    friendly_name: livingroom_tracking_light_23
  '0xe0798dfffecc8576':
    friendly_name: kid_small_bedroom_climate
  '0xf4b3b1fffe9910ff':
    friendly_name: kitchen_climate
  '0xa4c138e02b828b6b':
    friendly_name: doghouse_hotfloor
  '0xa4c13887efe3d4ca':
    friendly_name: kitchen_main_light_toggler
  '0xa4c138d9f081d74c':
    friendly_name: kitchen_stove
  '0x00158d0008c76a5e':
    friendly_name: main_entrance_lock
  '0x842712fffe412c67':
    friendly_name: main_entrance_outside_light
  '0x842712fffe415c44':
    friendly_name: entrance_room_light
  '0xa4c13832e273637f':
    friendly_name: kitchen_bar_light_toggler
    vibration_timeout: 0
  '0x00158d0008c7b364':
    friendly_name: '0x00158d0008c7b364'
  '0xa4c138ce135e538a':
    friendly_name: terace_door_lock
  '0xa4c138b6e99fbf5f':
    friendly_name: livingroom_tv
  '0x001788010916b368':
    friendly_name: entrance_room_motion
  '0xa4c138a24835333a':
    friendly_name: kid_bathroom
    state_action: false
  '0xa4c13839d09f599d':
    friendly_name: curtain_outside_power
  '0xa4c1385f3fdd900f':
    friendly_name: '0xa4c1385f3fdd900f'
  '0x00124b002a65b1bd':
    friendly_name: terrace_door_open
  '0xa4c138cc44e30809':
    friendly_name: hot_water_pump
  '0xa4c138a282e05367':
    friendly_name: cabinet_map_light
  '0x0ceff6fffe1a2c75':
    friendly_name: kitchen_additional_light
  '0x00124b002919ab73':
    friendly_name: kitchen_motion
  '0x70b3d52b60069ed9':
    friendly_name: kid_bathroom_towel_dryer
advanced:
  pan_id: 6754
  log_level: warn
external_converters:
  - converters/TS0601.js
