input_boolean:
  livingroom_automatic_light:
    name: Автоматичне керування світлом у вітальні

template:
  - binary_sensor:
      - name: livingroom_low_light_level
        state: >- 
          {{ 
            states('sun.sun') == 'below_horizon' or 
            states('sensor.livingroom_light_level') | float(0) <= 40
          }}

automation:
- id: toggle_livingroom_main_light
  alias: "Керуванням світла у вітальні"
  mode: parallel
  trigger: 
    - platform: state
      entity_id: binary_sensor.livingroom_entertainment_occupancy
      to: "on"
      variables:
        light_entity_ids: 
          - light.livingroom_tracking_light_21
          - light.livingroom_tracking_light_22
          - light.livingroom_tracking_light_23
          - light.livingroom_tracking_light_24
    - platform: state
      entity_id: binary_sensor.livingroom_entertainment_occupancy
      to: "off"
      for: 00:00:05
      variables:
        light_entity_ids: 
          - light.livingroom_tracking_light_21
          - light.livingroom_tracking_light_22
          - light.livingroom_tracking_light_23
          - light.livingroom_tracking_light_24
    - platform: state
      entity_id: binary_sensor.livingroom_projector_occupancy
      to: "on"
      variables:
        light_entity_ids: 
          - light.livingroom_tracking_light_11
          - light.livingroom_tracking_light_12
          - light.livingroom_tracking_light_13
          - light.livingroom_tracking_light_14
    - platform: state
      entity_id: binary_sensor.livingroom_projector_occupancy
      to: "off"
      for: 00:00:05
      variables:
        light_entity_ids: 
          - light.livingroom_tracking_light_11
          - light.livingroom_tracking_light_12
          - light.livingroom_tracking_light_13
          - light.livingroom_tracking_light_14
    - platform: state
      entity_id: binary_sensor.kitchen_bar_occupancy
      to: "on"
      for: 00:00:03
      variables:
        light_entity_ids: [light.kitchen_bar]
  condition:
    - condition: template
      value_template: | 
        {{ 
            is_state('input_boolean.livingroom_automatic_light', 'on') and
            (trigger.to_state.state == 'on' and 
              is_state('binary_sensor.livingroom_low_light_level', 'on') or 
            trigger.to_state.state == 'off')
        }}
  action:
    - service_template: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: "{{ light_entity_ids | list }}"

- id: toggle_kitchen_light
  mode: parallel
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_bar_occupancy
      to: "off"
      variables:
        light_entity_ids: [light.kitchen_bar]
    - platform: state
      entity_id: binary_sensor.livingroom_kitchen_occupancy
      to: "on"
      variables:
        light_entity_ids: [light.kitchen_light]
    - platform: state
      entity_id: binary_sensor.livingroom_kitchen_occupancy
      to: "off"
      for: 00:00:05
      variables:
        light_entity_ids: [light.kitchen_light]    
  condition:
    - condition: template
      value_template: | 
        {{ 
            trigger.to_state.state == 'on' and 
              is_state('binary_sensor.livingroom_low_light_level', 'on') or 
            trigger.to_state.state == 'off'
        }}
  action:
    - service_template: "light.turn_{{ trigger.to_state.state }}"
      target:
        entity_id: "{{ light_entity_ids | list }}"