automation:
  - id: notify_about_crossed_regions_house_entrance
    alias: Notify about IVS
    mode: parallel
    max: 20
    trigger:
      - platform: event
        event_type: dahua_event_received
        event_data:
          action: Start
          Code: CrossLineDetection
        variables:
          photo_path: "/tmp/snapshots/{{ now().timestamp() }}.jpg" 
      - platform: event
        event_type: dahua_event_received
        event_data:
          action: Start
          Code: CrossRegionDetection
        variables:
          photo_path: "/tmp/snapshots/{{ now().timestamp() }}.jpg" 
    action:
      - service: camera.snapshot
        target:
          entity_id: >-
            {% set entity_name_to_id = {
              'Camera house entrance': 'camera.camera_house_entrance_sub',
              'Camera house terace': 'camera.camera_house_terace_sub',
              'Camera house east': 'camera.camera_house_east_sub',
              'Camera garage gates': 'camera.camera_garage_gates_sub',
              'Camera garage back': 'camera.camera_garage_back_sub',
              'Camera between house and garage': 'camera.camera_between_house_and_garage_sub',
            } %}
            {{ entity_name_to_id[trigger.event.data.DeviceName] }}
        data:
          filename: "{{ photo_path }}"
      # - service: notify.telegram_serhii
      #   data:
      #     title: "Рух у дворі"
      #     message: |
      #       Зона: {{ trigger.event.data.data.Name | replace('_', ' ') }}
      - service: notify.telegram_serhii
        data:
          message: ""
          data:
            photo: 
              file: "{{ photo_path }}"
              caption: | 
                Зона: {{ trigger.event.data.data.Name | replace('_', ' ') }}

  - id: guests_via_main_entrance
    trigger:
      platform: event
      event_type: dahua_event_received
      event_data:
        action: Start
        Code: CrossLineDetection
      variables:
        photo_path: "/tmp/snapshots/{{ now().timestamp() }}.jpg"
    condition:
      - condition: template
        value_template: |
          {% set event = trigger.event.data.data %}
          {{ 
            event.Direction == 'LeftToRight' and 
            event.Name == 'yard_gates' and
            event.Object.ObjectType == 'Human'
          }}
    action:   
      - service: notify.telegram_serhii
        data:
          message: ""
          data:
            photo: 
              file: "{{ photo_path }}"
              caption: | 
                Прийшли гості