automation:
  - id: notify_about_ivs
    alias: Notify about IVS
    mode: parallel
    max: 50
    trigger:
      platform: event
      event_type: dahua_event_received
      event_data:
        action: Start
      variables:
        photo_path: "/tmp/snapshots/{{ now().timestamp() }}.jpg" 
        base_entity_id: >-
          {{ trigger.event.data.DeviceName | replace(' ', '_') | lower }}
    condition:
      - condition: template
        value_template: |
          {{
            trigger.event.data.Code in ['CrossLineDetection', 'CrossRegionDetection'] and
            ( 
              is_state('group.residents', 'not_home')
            )
          }} 
    action:
      - service: camera.snapshot
        target:
          entity_id: "camera.{{ base_entity_id }}_sub"
        data:
          filename: "{{ photo_path }}"
      - event: important_home_event
        event_data:
          message: |
            Зона: {{ trigger.event.data.data.Name | replace('_', ' ') }}
            {% if is_state('binary_sensor.' + base_entity_id + '_smart_motion_human', 'on') %}
              Помічена людина
            {% endif %}
            {% if is_state('binary_sensor.' + base_entity_id + '_smart_motion_vehicle', 'on') %}
              Помічена автівка
            {% endif %}
          attachments:
            - "{{ photo_path }}"

  - id: notify_about_other_camera_events
    alias: Notify about other camera events
    mode: parallel
    max: 100
    trigger:
      platform: event
      event_type: dahua_event_received
    condition:
      - condition: template
        value_template: | 
          {{ 
            trigger.event.data.Code not in [
              'CrossLineDetection', 
              'CrossRegionDetection',
              'VideoMotion',
              'SmartMotionHuman',
              'SmartMotionVehicle'
            ] 
          }}
    action:
      - event: important_home_event
        event_data:
          message: "Подія з камери: {{ trigger.event.data.Code }}"

  - id: proxy_dahua_cross_line_events
    mode: parallel
    max: 100
    trigger:
      platform: event
      event_type: dahua_event_received
      event_data:
        action: Start
        Code: CrossLineDetection
      variables:
        event: "{{ trigger.event.data.data }}"
    action:
      - event: yard_crossed_line
        event_data: 
          name: "{{ event.Name }}"
          direction: "{{ event['Direction'] }}"
          object_type: "{{ event['Object']['ObjectType'] }}"
          original: "{{ trigger.event.data }}"

  - id: proxy_dahua_cross_region_events
    mode: parallel
    max: 100
    trigger:
      platform: event
      event_type: dahua_event_received
      event_data:
        action: Start
        Code: CrossRegionDetection
      variables:
        event: "{{ trigger.event.data.data }}"
    action:
      - event: yard_crossed_region
        event_data: 
          name: "{{ event.Name }}"
          direction: "{{ event['Direction'] }}"
          object_type: "{{ event['Object']['ObjectType'] }}"
          original: "{{ trigger.event.data }}"
