- id: sync_heating_over_ebus
  alias: Синхронізація температур нагріву через Ebus
  trigger:
    - platform: time_pattern
      minutes: "/2"
    - platform: state
      entity_id: 
        - input_boolean.heating_enabled
        - input_boolean.hwc_enabled
        - input_number.main_heater_storage_temp_desired 
        - input_select.heating_mode
        - input_select.heating_preset
  action:
    - service: python_script.heating_ebus_sync
  mode: restart


- id: sync_heating_switch_state_over_ebus
  alias: Автотиматична синхронізація стану опалення по Ebus (якщо котел включиться коли має бути вимкнутий)
  mode: parallel
  trigger:
    - platform: state
      entity_id: switch.ebusd_bai_heatingswitch_onoff
      variables:
        expected_value: "{{ states('input_boolean.heating_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_heatingswitch_onoff
    - platform: state
      entity_id: switch.ebusd_bai_hwcswitch_onoff
      variables:
        expected_value: "{{ states('input_boolean.hwc_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_hwcswitch_onoff
    - platform: state
      entity_id: input_boolean.heating_enabled
      variables:
        expected_value: "{{ states('input_boolean.heating_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_heatingswitch_onoff
    - platform: state
      entity_id: input_boolean.hwc_enabled
      variables:
        expected_value: "{{ states('input_boolean.hwc_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_hwcswitch_onoff
  condition:  
    - condition: template
      value_template: "{{ states(entity_id_to_sync) != expected_value }}"
  action:
    - service_template: "switch.turn_{{ expected_value }}"
      target: 
        entity_id: "{{ entity_id_to_sync }}"

- id: notify_about_heating
  alias: 'Нотифікація про включення нагріву'
  trigger:
    - platform: state
      entity_id: binary_sensor.ebusd_bai_flame
      for: 00:01:00
  action:
  - event: important_home_event
    event_data:
      message: |
        *Режим котла:* {{ states('sensor.ebusd_bai_state') }}
        ⚡ *Підігрів* {{ states('binary_sensor.ebusd_bai_flame') }}, потужність {{ states('sensor.main_heater_current_power') }}
        ♨ *Температура* {{ states('sensor.ebusd_bai_flowtemp_temp') }} / {{ states('sensor.ebusd_bai_flowtempdesired_temp') }}
        ️🚰 *ГВС* {{ states('sensor.ebusd_bai_storagetemp_temp') }} / {{ states('sensor.ebusd_bai_storagetempdesired_temp') }}
  mode: single

- id: heating_abnormal_water_pressure
  alias: "Нотифікація про не нормальний тиск в опаленні"
  trigger:
    - platform: numeric_state
      entity_id: sensor.ebusd_bai_waterpressure_press
      above: 2.5
    - platform: numeric_state
      entity_id: sensor.ebusd_bai_waterpressure_press
      below: 1.2
  action:
    - service: persistent_notification.create
      data:
        title: "⚠ - Warning!"
        message: |
          Критичний тиск теплоносія: <b>{{ states('sensor.ebusd_bai_waterpressure_press') }}</b>
  mode: single

- id: save_last_heating_temperature
  alias: "Збереження останнього значення температури носія перед переключення клапана ГВС"
  trigger:
    - platform: state
      entity_id: sensor.ebusd_bai_positionvalveset
      from: Heating
  action:
    - service: input_number.set_value
      data:
        value: "{{ states('sensor.ebusd_bai_flowtemp_temp') | float }}"
      target:
        entity_id: input_number.heating_last_flowtemp
  mode: restart 

- id: enable_heating
  alias: Керування опаленням 
  trigger:
    platform: state
    entity_id: binary_sensor.requires_heating_in_house
    variables:
      heating_state: "{{ trigger.to_state.state }}"
    for: "00:00:03"
  action:
    - service_template: "input_boolean.turn_{{ heating_state }}"
      entity_id: input_boolean.heating_enabled

- id: sync_fake_thermostat_driven_switches_with_real
  mode: queued
  max: 50
  alias: Синхронізація клапанів керованих термостатом з реальними
  trigger:
    - platform: state
      entity_id:
        - climate.master_bedroom
        - climate.master_bathroom_hotfloor
        - climate.cabinet
        - climate.kid_small_bedroom
        - climate.kid_big_bedroom
        - climate.kid_bathroom_hotfloor
        - climate.livingroom
        - climate.livingroom_hotfloor_table
        - climate.livingroom_hotfloor_fireplace
        - climate.livingroom_hotfloor_exit
        - climate.kitchen_hotfloor
        - climate.entrance_room_hotfloor
      attribute: hvac_action
      for: "00:00:02"
    - platform: state
      entity_id: 
        - input_boolean.heating_enabled
        - input_select.heating_preset
  action:
    - service: script.sync_heater_valves
      data: {}

- id: toggle_hot_floor_pump
  alias: Керування насосом теплої підлоги (ТП)
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.hot_floor_pump_required
      to: 'on'
      variables:
        pump_state: 'on'
    - platform: state
      entity_id: binary_sensor.hot_floor_pump_required
      to: 'off'
      variables:
        delay_turn_off: "{{ now() + timedelta(hours=1) }}"
        pump_state: "{{ states('binary_sensor.is_hot_floor_valves_open') }}"
    - platform: time
      at: input_datetime.disable_hot_floor_pump_at
      variables:
        pump_state: 'off'
  action:
    - alias: Set pump turn off time
      service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.disable_hot_floor_pump_at
      data:
        datetime: "{{ delay_turn_off if delay_turn_off is defined and pump_state == 'on' else as_datetime(0) }}"
    - if: 
        - condition: template
          value_template: "{{ not is_state('switch.hot_floor_pump', pump_state) }}"
      then:
        - alias: Toggle pump
          service_template: "switch.turn_{{ pump_state }}"
          entity_id: switch.hot_floor_pump

- id: toggle_heating_thermostats_based_on_heating_preset
  alias: Керування термостатами по режиму опалюванню
  mode: restart
  trigger:
    - platform: state
      entity_id: input_select.heating_preset
      variables: 
        thermostats_to_be_enabled: | 
          {% if trigger.to_state.state == 'both' %}
            {{
              states.climate
                | selectattr('attributes.location', 'eq', 'house')
                | map(attribute='entity_id')
                | list 
            }}
          {% elif trigger.to_state.state == 'only_hot_floor_eco' %}
            {{ states.climate 
              | selectattr('attributes.location', 'eq', 'house')
              | selectattr('attributes.heater_type', 'eq', 'hotfloor')
              | selectattr('attributes.heater_importance', 'eq', 'high') 
              | map(attribute='entity_id')
              | list 
            }}
          {% elif trigger.to_state.state == 'only_radiators' %}
            {{ states.climate 
              | selectattr('attributes.location', 'eq', 'house')
              | selectattr('attributes.heater_type', 'eq', 'radiator')
              | map(attribute='entity_id')
              | list 
            }}
          {% elif trigger.to_state.state == 'only_hot_floor' %}
            {{ states.climate 
              | selectattr('attributes.location', 'eq', 'house')
              | selectattr('attributes.heater_type', 'eq', 'hotfloor')
              | map(attribute='entity_id')
              | list 
            }}
          {% endif %}
        thermostats_to_enable: |
          {{ thermostats_to_be_enabled 
            | reject('is_state', 'heat') 
            | list }}
        thermostats_to_disable: | 
          {{
            states.climate
              | selectattr('attributes.location', 'eq', 'house')
              | selectattr('state', 'eq', 'heat')
              | map(attribute='entity_id')
              | reject('in', thermostats_to_be_enabled)
              | list 
          }}
  action:
    - if: 
      - condition: template
        value_template: "{{ thermostats_to_disable | count > 0 }}"
      then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: "{{ thermostats_to_disable }}"
    - if: 
      - condition: template
        value_template: "{{ thermostats_to_enable | count > 0 }}"
      then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "heat"
        target:
          entity_id: "{{ thermostats_to_enable }}"

- id: control_hwc
  alias: Керування бойлером
  trigger:
    - platform: template
      value_template: |
        {{ 
          states('sensor.solcast_pv_forecast_forecast_this_hour') | float(0) >= 1500 and
          5 <= now().hour <= 19
        }}
      variables:
        heater_state: "on"
    - platform: template
      value_template: |
        {{ 
          states('sensor.solcast_pv_forecast_forecast_this_hour') | float(0) < 1500 and
          5 <= now().hour <= 19
        }}
      variables:
        heater_state: "off"
    - platform: time
      at: "04:00:00"
      variables:
        heater_state: "{{ states('binary_sensor.inverter_connected_to_grid') }}"
    - platform: time
      at: "07:00:00"
      variables:
        heater_state: "off"
  action:
    - if:
        - condition: template
          value_template: "{{ now().strftime('%a') == 'Sat' and trigger.platform == 'time' }}"
      then:
        - service_template: "input_boolean.turn_{{ heater_state }}"
          target:
            entity_id: input_boolean.hwc_enabled
      else:
        - alias: Ввімкнути/Вимкнути бойлер
          service_template: switch.turn_{{ heater_state }}
          entity_id: switch.water_heater_2k
  mode: restart

- id: disable_boiler_heating_if_no_electricity
  trigger:  
    - platform: state
      entity_id: binary_sensor.inverter_connected_to_grid
      from: 'on'
      to: 'off'
  condition:
    - condition: template
      value_template: "{{ is_state('switch.water_heater_2k', 'on') and 1 <= now().hour <= 7 }}"
  action:
    - service: switch.turn_off
      entity_id: switch.water_heater_2k
  
- id: toggle_thermostats_mode
  alias: Toggle thermostats mode
  trigger:
    - platform: state
      entity_id: input_select.family_state
      variables:
        may_set: "{{ now().hour > 18 }}"
        preset_mode: "sleep"
    - platform: state
      entity_id: binary_sensor.is_day_cheap_heating_period
      variables:
        preset_mode: "{{ 'comfort' if trigger.to_state.state == 'on' else 'home' }}"
    - platform: state
      entity_id: group.residents
      variables: 
        preset_mode: "{{ 'sleep' if trigger.to_state.state == 'not_home' else 'home' }}"
  condition:
    - condition: template
      value_template: "{{ may_set is not defined or may_set }}"
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: "{{ preset_mode }}"
      target:
        entity_id: | 
          {{ 
            states.climate 
              | selectattr('attributes.location', 'eq', 'house') 
              | map(attribute="entity_id") 
              | list 
          }}

- id: configure_heater_heating_mode_and_preset
  trigger:
    - platform: state
      entity_id: binary_sensor.is_cheap_heating_period
  action:
    - if:
      - condition: "template"
        value_template: "{{ states('input_select.heating_mode') != 'auto' }}"
      then:
        - service: input_select.select_option
          target:
            entity_id: input_select.heating_mode
          data:
            option: auto
    - service: input_select.select_option
      target:
        entity_id: input_select.heating_preset
      data:
        option: "{{ 'both' if trigger.to_state.state == 'on' else 'only_hot_floor_eco' }}"
    - if:
      - condition: template
        value_template: "{{ trigger.to_state.state == 'off' and is_state('input_boolean.hwc_enabled', 'on') }}"
      then:
      - service: input_boolean.turn_off
        entity_id: input_boolean.hwc_enabled