- id: sync_heating_over_ebus
  alias: Синхронізація температур нагріву через Ebus
  trigger:
    - platform: time_pattern
      minutes: "/2"
    - platform: state
      entity_id: 
        - input_boolean.heating_enabled
        - input_boolean.hwc_enabled
        - input_number.main_heater_storage_temp_desired 
  action:
    - service: python_script.heating_ebus_sync
  mode: restart


- id: sync_heating_switch_state_over_ebus
  alias: Автотиматична синхронізація стану опалення по Ebus (якщо котел включиться коли має бути вимкнутий)
  mode: parallel
  trigger:
    - platform: state
      entity_id: switch.ebusd_bai_heatingswitch_onoff
      variables:
        expected_value: "{{ states('input_boolean.heating_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_heatingswitch_onoff
    - platform: state
      entity_id: switch.ebusd_bai_hwcswitch_onoff
      variables:
        expected_value: "{{ states('input_boolean.hwc_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_hwcswitch_onoff
    - platform: state
      entity_id: input_boolean.heating_enabled
      variables:
        expected_value: "{{ states('input_boolean.heating_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_heatingswitch_onoff
    - platform: state
      entity_id: input_boolean.hwc_enabled
      variables:
        expected_value: "{{ states('input_boolean.hwc_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_hwcswitch_onoff
  condition:  
    - condition: template
      value_template: "{{ states(entity_id_to_sync) != expected_value }}"
  action:
    - service_template: "switch.turn_{{ expected_value }}"
      target: 
        entity_id: "{{ entity_id_to_sync }}"

- id: notify_about_heating
  alias: 'Нотифікація про включення нагріву'
  trigger:
    - platform: state
      entity_id: binary_sensor.ebusd_bai_flame
      for: 00:01:00
  action:
  - service: notify.telegram_serhii
    data:
      message: |
        *Режим котла:* {{ states('sensor.ebusd_bai_state') }}
        ⚡ *Підігрів* {{ states('binary_sensor.ebusd_bai_flame') }}, потужність {{ states('sensor.main_heater_current_power') }}
        ♨ *Температура* {{ states('sensor.ebusd_bai_flowtemp_temp') }} / {{ states('sensor.ebusd_bai_flowtempdesired_temp') }}
        ️🚰 *ГВС* {{ states('sensor.ebusd_bai_storagetemp_temp') }} / {{ states('sensor.ebusd_bai_storagetempdesired_temp') }}
  mode: single

- id: heating_abnormal_water_pressure
  alias: "Нотифікація про не нормальний тиск в опаленні"
  trigger:
    - platform: numeric_state
      entity_id: sensor.ebusd_bai_waterpressure_press
      above: 2.5
    - platform: numeric_state
      entity_id: sensor.ebusd_bai_waterpressure_press
      below: 1.2
  action:
    - service: persistent_notification.create
      data:
        title: "⚠ - Warning!"
        message: |
          Критичний тиск теплоносія: <b>{{ states('sensor.ebusd_bai_waterpressure_press') }}</b>
  mode: single

- id: save_last_heating_temperature
  alias: "Збереження останнього значення температури носія перед переключення клапана ГВС"
  trigger:
    - platform: state
      entity_id: sensor.ebusd_bai_positionvalveset
      from: Heating
  action:
    - service: input_number.set_value
      data:
        value: "{{ states('sensor.ebusd_bai_flowtemp_temp') | float }}"
      target:
        entity_id: input_number.heating_last_flowtemp
  mode: restart 

- id: enable_heating
  alias: Керування опаленням по часу
  trigger:
    - platform: time
      at: '23:05'
      variables:
        heating_state: 'on'
    - platform: time
      at: '07:00'
      variables:
        heating_state: 'off'
    # - platform: time
    #   at: '12:00'
    #   variables: 
    #     heating_state: 'on'
    - platform: time
      at: '15:00'
      variables: 
        heating_state: 'off'
  action:
    - if:
      - condition: "template"
        value_template: "{{ states('input_select.heating_mode') != 'auto' }}"
      then:
        - service: input_select.select_option
          target:
            entity_id: input_select.heating_mode
          data:
            option: auto
    - if:
      - condition: "template"
        value_template: "{{ states('input_select.heating_preset') != 'both' }}"
      then:
        - service: input_select.select_option
          target:
            entity_id: input_select.heating_preset
          data:
            option: both
    - service_template: input_boolean.turn_{{ heating_state }}
      entity_id: input_boolean.heating_enabled
    - if:
      - condition: template
        value_template: "{{ heating_state == 'off' and is_state('input_boolean.hwc_enabled', 'on') }}"
      then:
      - service: input_boolean.turn_off
        entity_id: input_boolean.hwc_enabled

- id: toggle_hot_floor_pump
  alias: Керування насосом теплої підлоги (ТП)
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.hot_floor_pump_required
      to: 'on'
      variables:
        pump_state: 'on'
    - platform: state
      entity_id: binary_sensor.hot_floor_pump_required
      to: 'off'
      variables:
        delay_turn_off: "{{ now() + timedelta(hours=1) }}"
        pump_state: "{{ states('binary_sensor.is_hot_floor_valves_open') }}"
    - platform: time
      at: input_datetime.disable_hot_floor_pump_at
      variables:
        pump_state: 'off'
  action:
    - alias: Set pump turn off time
      service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.disable_hot_floor_pump_at
      data:
        datetime: "{{ delay_turn_off if delay_turn_off is defined and pump_state == 'on' else as_datetime(0) }}"
    - if: 
        - condition: template
          value_template: "{{ not is_state('switch.hot_floor_pump', pump_state) }}"
      then:
        - alias: Toggle pump
          service_template: "switch.turn_{{ pump_state }}"
          entity_id: switch.hot_floor_pump

- id: control_heating_valves
  alias: Керування кранами опалення в залежності від температури
  mode: queued
  max: 24
  trigger:
    - platform: state
      entity_id: binary_sensor.heating_valve_open_master_bedroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_master_bedroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_master_bathroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_master_bathroom_hot_floor]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_cabinet
      variables:
        valve_switch_entity_id: [switch.heater_valve_cabinet]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kid_small_bedroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_kid_small_bedroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kid_big_bedroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_kid_big_bedroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kid_bathroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_hall_and_small_bathroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_living_room
      variables:
        valve_switch_entity_id: [switch.heater_valve_livingroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_living_room_hot_floor
      variables:
        valve_switch_entity_id: 
          - switch.heater_valve_hot_floor_livingroom3
          - switch.heater_valve_hot_floor_livingroom2
          - switch.heater_valve_hot_floor_livingroom1
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kitchen
      variables:
        valve_switch_entity_id: [switch.heater_valve_kitchen_hot_floor]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_entrance_room
      variables:
        valve_switch_entity_id: [switch.heater_valve_hot_floor_entrance_tech_room]
  action:
    # normal open valves require power to close the valve
    - service_template: "switch.turn_{{ 'off' if trigger.to_state.state == 'on' else 'on' }}"
      target:
        entity_id: "{{ valve_switch_entity_id | list }}"

# - id: open_valves_on_collector_if_no_heating
#   alias: Вікдрити крани на колекторі якщо вимкнене опалення
#   trigger:
#     platform: state
#     entity_id: input_boolean.heating_enabled
#     to: 'off'
#   action:
#     - service: switch.turn_off
#       entity_id: 
#         - switch.heater_valve_master_bedroom
#         - switch.heater_valve_master_bathroom_hot_floor
#         - switch.heater_valve_cabinet
#         - switch.heater_valve_kid_small_bedroom
#         - switch.heater_valve_kid_big_bedroom
#         - switch.heater_valve_hall_and_small_bathroom
#         - switch.heater_valve_livingroom
#         - switch.heater_valve_hot_floor_livingroom3
#         - switch.heater_valve_hot_floor_livingroom2
#         - switch.heater_valve_hot_floor_livingroom1
#         - switch.heater_valve_kitchen_hot_floor
#         - switch.heater_valve_hot_floor_entrance_tech_room

- id: control_hwc
  alias: Керування бойлером
  trigger:
    - platform: template
      value_template: |
        {{ 
          states('sensor.solcast_pv_forecast_forecast_this_hour') | float(0) >= 1500 and
          5 <= now().hour <= 19
        }}
      variables:
        heater_state: "on"
    - platform: template
      value_template: |
        {{ 
          states('sensor.solcast_pv_forecast_forecast_this_hour') | float(0) < 1500 and
          5 <= now().hour <= 19
        }}
      variables:
        heater_state: "off"
    - platform: time
      at: "03:00:00"
      variables:
        heater_state: "on"
    - platform: time
      at: "05:50:00"
      variables:
        heater_state: "off"
  action:
    - if:
        - condition: template
          value_template: "{{ now().strftime('%a') == 'Sat' and trigger.platform == 'time' }}"
      then:
        - service_template: "input_boolean.turn_{{ heater_state }}"
          target:
            entity_id: input_boolean.hwc_enabled
      else:
        - alias: Ввімкнути/Вимкнути бойлер
          service_template: switch.turn_{{ heater_state }}
          entity_id: switch.water_heater_2k
  mode: restart
