- id: sync_heating_over_ebus
  alias: Синхронізація температур нагріву через Ebus
  trigger:
    - platform: time_pattern
      minutes: "/2"
    - platform: state
      entity_id: 
        - input_boolean.heating_enabled
        - input_boolean.hwc_enabled
        - input_number.main_heater_storage_temp_desired 
  action:
    - service: python_script.heating_ebus_sync
  mode: restart


- id: sync_heating_switch_state_over_ebus
  alias: Автотиматична синхронізація стану опалення по Ebus (якщо котел включиться коли має бути вимкнутий)
  mode: parallel
  trigger:
    - platform: state
      entity_id: switch.ebusd_bai_heatingswitch_onoff
      variables:
        expected_value: "{{ states('input_boolean.heating_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_heatingswitch_onoff
    - platform: state
      entity_id: switch.ebusd_bai_hwcswitch_onoff
      variables:
        expected_value: "{{ states('input_boolean.hwc_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_hwcswitch_onoff
    - platform: state
      entity_id: input_boolean.heating_enabled
      variables:
        expected_value: "{{ states('input_boolean.heating_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_heatingswitch_onoff
    - platform: state
      entity_id: input_boolean.hwc_enabled
      variables:
        expected_value: "{{ states('input_boolean.hwc_enabled') }}"
        entity_id_to_sync: switch.ebusd_bai_hwcswitch_onoff
  condition:  
    - condition: template
      value_template: "{{ states(entity_id_to_sync) != expected_value }}"
  action:
    - service_template: "switch.turn_{{ expected_value }}"
      target: 
        entity_id: "{{ entity_id_to_sync }}"

- id: notify_about_heating
  alias: 'Нотифікація про включення нагріву'
  trigger:
    - platform: state
      entity_id: binary_sensor.ebusd_bai_flame
      for: 00:01:00
  action:
  - service: notify.telegram_serhii
    data:
      message: |
        *Режим котла:* {{ states('sensor.ebusd_bai_state') }}
        ⚡ *Підігрів* {{ states('binary_sensor.ebusd_bai_flame') }}, потужність {{ states('sensor.main_heater_current_power') }}
        ♨ *Температура* {{ states('sensor.ebusd_bai_flowtemp_temp') }} / {{ states('sensor.ebusd_bai_flowtempdesired_temp') }}
        ️🚰 *ГВС* {{ states('sensor.ebusd_bai_storagetemp_temp') }} / {{ states('sensor.ebusd_bai_storagetempdesired_temp') }}
  mode: single

- id: heating_abnormal_water_pressure
  alias: "Нотифікація про не нормальний тиск в опаленні"
  trigger:
    - platform: numeric_state
      entity_id: sensor.ebusd_bai_waterpressure_press
      above: 2.5
    - platform: numeric_state
      entity_id: sensor.ebusd_bai_waterpressure_press
      below: 1.2
  action:
    - service: notify.telegram_serhii
      data:
        message: |
          Критичний тиск теплоносія: <b>{{ states('sensor.ebusd_bai_waterpressure_press') }}</b>
    - service: persistent_notification.create
      data:
        title: ⚠ - Warning!
        message: "Критичний тиск теплоносія: <b>{{ states('sensor.ebusd_bai_waterpressure_press') }}</b>"
  mode: single

- id: save_last_heating_temperature
  alias: "Збереження останнього значення температури носія перед переключення клапана ГВС"
  trigger:
    - platform: state
      entity_id: sensor.ebusd_bai_positionvalveset
      from: Heating
  action:
    - service: input_number.set_value
      data:
        value: "{{ states('sensor.ebusd_bai_flowtemp_temp') | float }}"
      target:
        entity_id: input_number.heating_last_flowtemp
  mode: restart 

- id: enable_heating
  alias: Керування опаленням по часу
  trigger:
    - platform: time
      at: '23:30'
      variables:
        heating_state: 'on'
    - platform: time
      at: '07:00'
      variables:
        heating_state: 'off'
    # - platform: time
    #   at: '12:00'
    #   variables: 
    #     heating_state: 'on'
    - platform: time
      at: '15:00'
      variables: 
        heating_state: 'off'
  action:
    - service_template: switch.turn_{{ heating_state }}
      entity_id: input_boolean.heating_enabled
    - if:
      - condition: template
        value_template: "{{ heating_state == 'off' and states('input_boolean.hwc_enabled') == 'on' }}"
      then:
      - service: switch.turn_off
        entity_id: input_boolean.hwc_enabled

- id: enable_hot_floor_pump
  alias: Ввімкнути насос теплої підлоги (ТП)
  trigger:
    - id: solar_on
      type: power
      platform: device
      device_id: 26ffd1f44a4fa883a5346115b3592da0
      entity_id: sensor.power_production_now
      domain: sensor
      above: 1000
    - id: heater_on
      platform: state
      entity_id: input_boolean.heating_enabled
      to: "on"
    - platform: numeric_state
      entity_id: sensor.fireplace_fan_power
      above: 1
  action:
    - alias: Enable pump
      service_template: switch.turn_on
      entity_id: switch.hot_floor_pump
  mode: single

- id: disable_hot_floor_pump
  alias: Вимкнути насос теплої підлоги (ТП)
  trigger:
    - id: solar_off
      type: power
      platform: device
      device_id: 26ffd1f44a4fa883a5346115b3592da0
      entity_id: sensor.power_production_now
      domain: sensor
      below: 999
      variables:
        scheduled_disabling: false
    - id: heater_off
      platform: state
      entity_id: input_boolean.heating_enabled
      to: "off"
      variables:
        scheduled_disabling: true
    - platform: time
      at: input_datetime.disable_hot_floor_pump_at
      variables:
        scheduled_disabling: false
    - platform: numeric_state
      entity_id: sensor.fireplace_fan_power
      below: 1
      variables:
        scheduled_disabling: true
  condition:
    - condition: template
      value_template: "{{ states('input_boolean.heating_enabled') == 'off' }}"
  action:
    - if: 
        - condition: template
          value_template: "{{ scheduled_disabling }}"
      then:
        - alias: Schedule pump disabling
          service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.disable_hot_floor_pump_at
          data:
            timestamp: "{{ now().timestamp() + 2 * 60 * 60 }}"
      else:
      - alias: Disable pump
        service_template: switch.turn_off
        entity_id: switch.hot_floor_pump
  mode: single

- id: control_heating_valves
  alias: Керування кранами опалення в залежності від температури
  mode: parallel
  max: 20
  trigger:
    - platform: state
      entity_id: binary_sensor.heating_valve_open_master_bedroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_master_bedroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_master_bathroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_master_bathroom_hot_floor]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_cabinet
      variables:
        valve_switch_entity_id: [switch.heater_valve_cabinet]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kid_small_bedroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_kid_small_bedroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kid_big_bedroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_kid_big_bedroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kid_bathroom
      variables:
        valve_switch_entity_id: [switch.heater_valve_hall_and_small_bathroom]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_living_room
      variables:
        valve_switch_entity_id: 
          - switch.heater_valve_livingroom
          # - switch.heater_valve_hot_floor_livingroom3
          - switch.heater_valve_hot_floor_livingroom2
          - switch.heater_valve_hot_floor_livingroom1
    - platform: state
      entity_id: binary_sensor.heating_valve_open_kitchen
      variables:
        valve_switch_entity_id: [switch.heater_valve_kitchen_hot_floor]
    - platform: state
      entity_id: binary_sensor.heating_valve_open_entrance_or_tech_room
      variables:
        valve_switch_entity_id: [switch.heater_valve_hot_floor_entrance_tech_room]
  action:
    # normal open valves require power to close the valve
    - service_template: "switch.turn_{{ 'off' if trigger.to_state.state == 'on' else 'on' }}"
      target:
        entity_id: "{{ valve_switch_entity_id | list }}"

- id: control_hwc
  alias: Керування бойлером
  trigger:
    - type: energy
      platform: device
      device_id: 26ffd1f44a4fa883a5346115b3592da0
      entity_id: sensor.energy_current_hour
      domain: sensor
      above: 1.5
      variables:
        heater_state: "on"
    - type: energy
      platform: device
      device_id: 26ffd1f44a4fa883a5346115b3592da0
      entity_id: sensor.energy_current_hour
      domain: sensor
      below: 1.5
      variables:
        heater_state: "off"
    - platform: time
      at: "03:00:00"
      variables:
        heater_state: "on"
    - platform: time
      at: "05:50:00"
      variables:
        heater_state: "off"
  action:
    - if:
        - condition: template
          value_template: "{{ now().strftime('%a') == 'Sat' and trigger.platform == 'time' }}"
      then:
        - service_template: "switch.turn_{{ heater_state }}"
          target:
            entity_id: input_boolean.hwc_enabled
      else:
        - alias: Ввімкнути/Вимкнути бойлер
          service_template: switch.turn_{{ heater_state }}
          entity_id: switch.water_heater_2k
  mode: restart
