automation: !include ./automations.yml
script: !include ./scripts.yml

homeassistant:
  customize:
    number.ebusd_bai_partloadhckw_power:
      max: 14
      min: 2
    number.ebusd_bai_partloadhwckw_power:
      max: 14
      min: 2
    number.ebusd_bai_hwctempmax_temp:
      min: 35
      max: 75
      step: 1
      mode: slider
    climate.master_bedroom:
      location: house
      heater_type: radiator 
    climate.master_bathroom_hotfloor:
      heater_type: hotfloor
      location: house
    climate.cabinet:
      heater_type: radiator
      location: house
    climate.kid_small_bedroom:
      heater_type: hotfloor
      location: house
    climate.kid_big_bedroom:
      heater_type: radiator
      location: house
    climate.kid_bathroom_hotfloor:
      heater_type: hotfloor
      location: house
    climate.livingroom:
      heater_type: radiator
      location: house
    climate.livingroom_hotfloor_table:
      heater_type: hotfloor
      heater_importance: high
      location: house
    climate.livingroom_hotfloor_fireplace:
      heater_type: hotfloor
      heater_importance: high
      location: house
    climate.livingroom_hotfloor_exit:
      heater_type: hotfloor
      heater_importance: high
      location: house
    climate.kitchen_hotfloor:
      heater_type: hotfloor
      heater_importance: high
      location: house
    climate.entrance_room_hotfloor:
      heater_type: hotfloor
      location: house
input_number: 
  main_heater_storage_temp_desired:
    name: Бажана темп. ГВС
    min: 35
    max: 70
    step: 1
    icon: mdi:thermometer-water
    unit_of_measurement: °C

input_datetime: 
  disable_hot_floor_pump_at:
    name: Час вимкнення насос гарячої підлоги
    icon: mdi:clock
    has_date: true
    has_time: true

input_select:
  heating_mode:
    name: Heating mode
    options:
      - minimum # 35 C
      - normal  # 40 C
      - fast    # 50 C
      - swift # 60 C
      - auto
    icon: mdi:heat-wave
  heating_preset:
    name: Heating preset
    options:
      - only_hot_floor
      - only_hot_floor_eco
      - only_radiators
      - both
input_boolean:
  heating_enabled:
    name: Включити опалення
  hwc_enabled: 
    name: Включити ГВС
  # because I have NO heating valves, I need thermostat to somewhere store its desired state
  # so then I can understand whether heating is required or not based on `hvac_action` attribute
  # and be able to optimize electisity usage by opening valves when heater doesn't heat
  thermostat_driven_heater_valve_master_bedroom:
  thermostat_driven_heater_valve_master_bathroom_hot_floor:
  thermostat_driven_heater_valve_cabinet:
  thermostat_driven_heater_valve_kid_small_bedroom:
  thermostat_driven_heater_valve_kid_big_bedroom:
  thermostat_driven_heater_valve_hall_and_small_bathroom:
  thermostat_driven_heater_valve_livingroom:
  thermostat_driven_heater_valve_hot_floor_livingroom1:
  thermostat_driven_heater_valve_hot_floor_livingroom2:
  thermostat_driven_heater_valve_hot_floor_livingroom3:
  thermostat_driven_heater_valve_kitchen_hot_floor:
  thermostat_driven_heater_valve_hot_floor_entrance_tech_room:

template:
  - sensor:
    - name: main_heater_current_power
      icon: mdi:flash
      device_class: power
      state_class: measurement
      state: |
        {% set max_power = 14 %}
        {% if states("binary_sensor.ebusd_bai_flame") == 'on' %}
          {{ states('sensor.ebusd_bai_modulationtempdesired') | float(0) * max_power / 100 | round(2) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: kW

    - name: main_heater_errors
      icon: mdi:alert-octagram
      state: |
        {% set sensors = [
          states('sensor.ebusd_bai_currenterror_error'), 
          states('sensor.ebusd_bai_currenterror_error_2'), 
          states('sensor.ebusd_bai_currenterror_error_3'), 
          states('sensor.ebusd_bai_currenterror_error_4'), 
          states('sensor.ebusd_bai_currenterror_error_5') 
        ] %}
        {% set result = sensors
          | reject('eq', 'None')
          | list
          | join(',\n')
        %}
        {{ 'none' if result == '' else result }}
    - name: house_min_heating_temp_diff
      state_class: measurement
      state: |
        {% set min = namespace(value=0) %}
        {% for entity in states.climate | selectattr('attributes.location', 'eq', 'house') | list %}
          {% if entity.state == 'heat' %}
            {% set diff = float(entity.attributes.current_temperature, 0) - float(entity.attributes.temperature, 0) %}
            {% set min.value = diff if min.value > diff else min.value %}
          {% endif %}
        {% endfor %}
        {{ min.value }}
        
  - binary_sensor: 
    - name: is_day_cheap_heating_period
      state: "{{ is_state('binary_sensor.is_cheap_heating_period', 'on') and is_state('binary_sensor.is_day_heating_time', 'on') }}"
    - name: is_hot_floor_valves_open
      state: |
        {{ ([
          states('switch.heater_valve_master_bathroom_hot_floor'),
          states('switch.heater_valve_hall_and_small_bathroom'),
          states('switch.heater_valve_hot_floor_livingroom3'),
          states('switch.heater_valve_hot_floor_livingroom2'),
          states('switch.heater_valve_hot_floor_livingroom1'),
          states('switch.heater_valve_kitchen_hot_floor'),
          states('switch.heater_valve_hot_floor_entrance_tech_room')
        ] | select('eq', 'on') | first) == 'on' }}
    - name: hot_floor_pump_required
      state: |
        {{
          is_state('binary_sensor.is_hot_floor_valves_open', 'on') and (
            float(states('sensor.fireplace_fan_power'), 0) > 0 or
            is_state('input_boolean.heating_enabled', 'on') or
            float(states('sensor.solcast_pv_forecast_forecast_this_hour'), 0) > 1000
          )
        }}
    - name: requires_heating_in_house
      state: |
        {{
          (states.climate 
            | selectattr('attributes.location', 'eq', 'house')
            | map(attribute='attributes.hvac_action')
            | select('eq', 'heating')
            | first) == 'heating'
        }}
    - name: heating_only_hotfloor_in_house
      state: |
        {% set thermostats_heating = states.climate 
          | selectattr('attributes.location', 'eq', 'house')
          | selectattr('attributes.hvac_action', 'eq', 'heating')
          | list
        %}
        {{
          (thermostats_heating 
            | selectattr('attributes.heater_type', 'eq', 'hotfloor') 
            | list 
            | count) == (thermostats_heating | count)
        }}
    
  - trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: event
      event_type: event_template_reloaded
    sensor:
    - name: main_heater_current_power_live
      icon: mdi:flash
      unit_of_measurement: "kW"
      device_class: power
      state_class: measurement
      state: >-
        {{ float(states('sensor.main_heater_current_power'), 0) }}
      attributes: 
        triggered_at: "{{ now() }}"
  - trigger:
    - platform: time
      at: ["05:00:00", "21:00:00"]
    - platform: event
      event_type: my_event_template_reloaded
    - platform: homeassistant
      event: start
    binary_sensor:
    - name: is_day_heating_time
      state: "{{ 5 <= now().hour <= 21 }}"
  - trigger:
    - platform: time
      at: ["23:00:00", "07:00:00"]
    - platform: event
      event_type: my_event_template_reloaded
    - platform: homeassistant
      event: start
    binary_sensor:
    - name: is_cheap_heating_period
      state: "{{ 23 <= now().hour or now().hour < 7 }}"
sensor:
  - platform: integration
    source: sensor.main_heater_current_power_live
    name: main_heater_energy
    round: 1
  - platform: min_max
    name: house_min_temp
    type: min
    round_digits: 1
    entity_ids:
      - sensor.cabinet_climate_temperature
      - sensor.kid_bathroom_climate_temperature
      - sensor.master_bathroom_climate_temperature
      - sensor.master_bedroom_climate_temperature
      - sensor.master_wardrobe_climate_temperature
      - sensor.living_room_climate_temperature
      - sensor.entrance_room_climate_temperature

climate:
  - platform: generic_thermostat
    name: master_bedroom
    heater: input_boolean.thermostat_driven_heater_valve_master_bedroom
    target_sensor: sensor.master_bedroom_climate_temperature
    away_temp: 15
    comfort_temp: 21
    home_temp: 19
    sleep_temp: 17
    precision: 0.1
  - platform: generic_thermostat
    name: master_bathroom_hotfloor
    heater: input_boolean.thermostat_driven_heater_valve_master_bathroom_hot_floor
    target_sensor: sensor.master_bathroom_climate_temperature
    away_temp: 15
    comfort_temp: 21
    home_temp: 19
    sleep_temp: 18
    precision: 0.1
  - platform: generic_thermostat
    name: cabinet
    heater: input_boolean.thermostat_driven_heater_valve_cabinet
    target_sensor: sensor.cabinet_climate_temperature
    away_temp: 15
    comfort_temp: 21
    home_temp: 19
    sleep_temp: 19
    precision: 0.1
  - platform: generic_thermostat
    name: kid_small_bedroom
    heater: input_boolean.thermostat_driven_heater_valve_kid_small_bedroom
    target_sensor: sensor.cabinet_climate_temperature # TODO: need sensor
    away_temp: 15
    comfort_temp: 21
    home_temp: 19
    sleep_temp: 17
    precision: 0.1
  - platform: generic_thermostat
    name: kid_big_bedroom
    heater: input_boolean.thermostat_driven_heater_valve_kid_big_bedroom
    target_sensor: sensor.kid_big_bedroom_climate_temperature
    away_temp: 15
    comfort_temp: 21
    home_temp: 19
    sleep_temp: 17
    precision: 0.1
  - platform: generic_thermostat
    name: kid_bathroom_hotfloor
    heater: input_boolean.thermostat_driven_heater_valve_hall_and_small_bathroom
    target_sensor: sensor.kid_bathroom_climate_temperature
    away_temp: 15
    comfort_temp: 22
    home_temp: 21
    sleep_temp: 20
    precision: 0.1
  - platform: generic_thermostat
    name: livingroom
    heater: input_boolean.thermostat_driven_heater_valve_livingroom
    target_sensor: sensor.living_room_climate_temperature
    away_temp: 15
    comfort_temp: 21
    home_temp: 20
    sleep_temp: 17
    precision: 0.1
  - platform: generic_thermostat
    name: livingroom_hotfloor_table
    heater: input_boolean.thermostat_driven_heater_valve_hot_floor_livingroom1
    target_sensor: sensor.living_room_climate_temperature
    away_temp: 7
    comfort_temp: 22
    home_temp: 21
    sleep_temp: 21
    precision: 0.1
  - platform: generic_thermostat
    name: livingroom_hotfloor_fireplace
    heater: input_boolean.thermostat_driven_heater_valve_hot_floor_livingroom2
    target_sensor: sensor.living_room_climate_temperature
    away_temp: 7
    comfort_temp: 22
    home_temp: 21
    sleep_temp: 21
    precision: 0.1
  - platform: generic_thermostat
    name: livingroom_hotfloor_exit
    heater: input_boolean.thermostat_driven_heater_valve_hot_floor_livingroom3
    target_sensor: sensor.living_room_climate_temperature
    away_temp: 10
    comfort_temp: 22
    home_temp: 21
    sleep_temp: 21
    precision: 0.1
  - platform: generic_thermostat
    name: kitchen_hotfloor
    heater: input_boolean.thermostat_driven_heater_valve_kitchen_hot_floor
    target_sensor: sensor.kitchen_climate_temperature
    away_temp: 10
    comfort_temp: 22
    home_temp: 21
    sleep_temp: 21
    precision: 0.1
  - platform: generic_thermostat
    name: entrance_room_hotfloor
    heater: input_boolean.thermostat_driven_heater_valve_hot_floor_entrance_tech_room
    target_sensor: sensor.entrance_room_climate_temperature
    away_temp: 10
    comfort_temp: 22
    home_temp: 20
    sleep_temp: 16
    precision: 0.1
