- id: define_energy_tariffs  
  alias: Select electricity tariff
  trigger:
    - platform: state
      entity_id: sensor.energy_tariff
  condition:
    - condition: template
      value_template: "{{ states('sensor.energy_tariff') != 'unknown' }}"
  action:
    - service: select.select_option
      target:
        entity_id: 
          - select.monthly_energy
      data:
        option: "{{ states('sensor.energy_tariff') }}"

- id: mot_energy_summary_to_residents
  alias: Відправка деталей про електрику
  initial_state: true
  trigger:
    - platform: time
      at: 07:00
      id: monthly_report
    - platform: event
      event_type: external_command
      event_data: 
        command: /energy_summary
      id: current_report
  condition:
    - condition: template
      value_template: |
        {{ trigger.id == 'current_report' or (trigger.id == 'monthly_report' and now().day == 1) }}
  action:
    - event: important_home_event
      event_data:
        message: |
          {% if trigger.id == 'monthly_report' %}
            {{"\U0001F4C5"}} Новий комунальний місяць
          {% else %}
            {{"\U0001F4C5"}} {{ now().strftime("%H:%M:%S %d.%m.%Y") }}
          {% endif %}  
          *Імпортовано*:
          {{"\U000026A1"}} Всього - {{ states('sensor.monthly_energy_total') }} КВт/год ({{ states('sensor.monthly_energy_total_cost') }} грн)
          {{"\U00002600"}} День - {{ states('sensor.monthly_energy_day') }} КВт/год ({{ states('sensor.monthly_energy_day_cost') }} грн)
          {{"\U0001F31A"}} Ніч - {{ states('sensor.monthly_energy_night') }} КВт/год ({{ states('sensor.monthly_energy_night_cost') }} грн)

- id: notify_when_main_power_lost
  alias: Notify when grid power lost
  mode: restart
  trigger:  
    # - platform: state
    #   entity_id: binary_sensor.has_connection_to_main
    #   from: 'off'
    #   to: 'on'
    #   for: "00:05:00"
    # - platform: state
    #   entity_id: binary_sensor.has_connection_to_main
    #   from: 'on'
    #   to: 'off'
    #   for: "00:05:00"
    - platform: event
      event_type: external_command
      event_data:
        command: /energy_main_state
  action: 
    - event: important_home_event
      event_data:
        message: | 
          {% if is_state('binary_sensor.has_connection_to_main', 'on') %}
            💡 Main electricity available.
          {% else %}
            💥 Lost electricity.
          {% endif %}
          Voltage:
          1. {{ states('sensor.power_consumption_voltage_x') }}V ({{ states('sensor.power_consumption_power_x') }}W)
          2. {{ states('sensor.power_consumption_voltage_y') }}V ({{ states('sensor.power_consumption_power_y') }}W)
          3. {{ states('sensor.power_consumption_voltage_z') }}V ({{ states('sensor.power_consumption_power_z') }}W)

- id: toggle_washing_machine_power_reservation
  alias: Toggle washing machine power reservation
  trigger: 
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      above: 1
      variables:
        reserve_power: 'on'
    - platform: numeric_state
      entity_id: sensor.washing_machine_power
      below: 600
      variables:
        reserve_power: 'off'
    - platform: state
      entity_id: sensor.washing_machine_power
      to: '0'
      variables:
        reserve_power: 'off'
  action:
    - service_template: "input_boolean.turn_{{ reserve_power }}"
      target:
        entity_id: input_boolean.washing_machine_power_reservation

      